# Generated by Django 3.1 on 2020-09-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Fighter',
        ),
    ]
