# Generated by Django 3.1 on 2020-09-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='caster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='casted', to='tracker.fighter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
